name: TimeToSleep-AndroidBuild
on:
  push:
    tags:
      - '*'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set the environment variable
        run: echo "BUILD_NAME=TimeToSleep-${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build with gradle
        run : ./gradlew build

      - name: Upload a BuildArtifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ env.BUILD_NAME}}.apk
          path: ${{ env.BUILD_NAME}}.apk


      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          prerelease: true
          files: |
            app/build/outputs/apk/release/${{ env.BUILD_NAME}}.apk
            app/build/outputs/bundle/release/${{ env.BUILD_NAME}}.aab