name: TimeToSleep-AndroidBuild
on:
  push:
    tags:
      - '*'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew


      - name: Build with gradle
        run : ./gradlew build

      - name: Upload a BuildArtifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: TimeToSleep-${{ github.event.release.tag_name }}.apk
          path: app/build/outputs/apk/release/TimeToSleep-${{ github.event.release.tag_name }}.apk.apk


      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          prerelease: true
          files: |
            app/build/outputs/apk/release/TimeToSleep-${{ github.event.release.tag_name }}.apk.apk
            app/build/outputs/bundle/release/TimeToSleep-${{ github.event.release.tag_name }}.apk.aab